---
- name: Add lines to myfile - Version 2
  hosts: localhost
  tasks:
    - name: adding 2 lines to myfile under git repository
      blockinfile:
        path: /root/git_repositories/ansible_palybooks/myfile
        create: yes
        block: |
          This is line 1
          This is line 2
