---
- name: Check free and disk free memory
  hosts: all
  tasks:
    - name: Check free memory
      command: free -m
      register: free_ouput

    - name: PrintOutput of Check Memory
      debug:
        var: free_output

    - name: Check Disk
      command: df -h
      register: disk_output

    - name: Print Output of Check Disk
      debug:
        var: disk_output
        